### ISSUE TITLE
Jade Support

### ISSUE THREAD

**Issue by DylanPiercey** [STRd6/hamlet#14]
I love hamlet and have been using it in some little demo's lately and it's integration with coffee-script is top-notch. 

However I feel like you could reach a broader audience if you also supported jade templates. Many nodejs developers use jade templates, and I for one even compile jade templates for static sites. I'd love to use hamlet in production however it'd be hard to switch my codebase from jade.

**Comment by STRd6** [comment]
This has been in since a while ago, sorry I haven't updated the issue! We're actually using the jade syntax in production on some projects so I think it should be pretty good now.

If you have a `templates` folder with `.jade` files in it, then this command will compile them:

`./node_modules/.bin/hamlet -d templates -r "require('hamlet.coffee')"`
